stages:
  - test
  - build image
  - publish-docs-if-changed
  - trigger deploy
  - static scans
  - publish pages

variables:
  # VAULT_ADDR: defined in GitLab variables
  # The same image have to be used by test and code coverage jobs:
  TEST_IMAGE: advancedtelematic/gitlab-jobs:0.2.5

test:
  stage: test
  except:
    refs:
      - deploy/sit
  image: $TEST_IMAGE
  script:
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 "project ota-plus-web" ut:test
  cache:
    paths:
      - .ivy2/
      - .sbt/

code coverage:
  extends: .report_scala_coverage
  allow_failure: true
  image: $TEST_IMAGE
  script:
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 "project ota-plus-web" clean coverageOn ut:test coverageOff coverageReport sonarScan
    - mkdir -p target/scala-2.12/coverage-report
    - cp ota-plus-web/target/scala-2.12/coverage-report/cobertura.xml target/scala-2.12/coverage-report/cobertura.xml

build docker image:
  stage: build image
  except:
    refs:
      - schedules
      - deploy/sit
  only:
    refs:
      - master
  tags:
    - docker-sock
  image: advancedtelematic/app-gitlab-job:0.0.2
  script:
    - env | sort
    - export VAULT_TOKEN=$(cat /opt/vault/token)
    - gitlab-docker-login $VAULT_ADDR
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 -batch ";project ota-plus-web;release" -Dsbt.log.noformat=true
  cache:
    paths:
      - .ivy2/
      - .sbt/

trigger dev deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - master
  variables:
    ENV: "dev"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: app
    CREATE_COMMIT: "true"
    UPSTREAM_COMMIT_MESSAGE: $CI_COMMIT_MESSAGE
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master

trigger sit deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - deploy/sit
  variables:
    ENV: "sit"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: app
    CREATE_COMMIT: "true"
    UPSTREAM_COMMIT_MESSAGE: $CI_COMMIT_MESSAGE
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master

trigger-docsite-build:
  stage: publish-docs-if-changed
  except:
    - schedules
  only:
    refs:
      - master
    changes:
      - ota-plus-web/docs/**/*
  trigger:
    project: olp/edge/ota/documentation/ota-connect-docs
    branch: master


include:
  - template: SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - project: olp/edge/ota/infra/security
    ref: v0.0.9
    file: /shared.yaml
