stages:
  - test
  - build image
  - trigger deploy
  - publish-docs-if-changed
  - veracode scan
  - deps scan
  - generate pages


variables:
  VAULT_ADDR: "http://vault.sit-ota.aws.in.here.com"

test:
  stage: test
  tags:
    - docker-sock
  image: advancedtelematic/gitlab-jobs:0.2.3
  script:
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 ota-plus-web/ut:test
  cache:
    paths:
      - .ivy2/
      - .sbt


build docker image:
  stage: build image
  except:
    - schedules
  only:
    - master
  tags:
    - docker-sock
  image: advancedtelematic/app-gitlab-job:0.0.1
  script:
    - env | sort
    - export VAULT_TOKEN=$(cat /opt/vault/token)
    - gitlab-docker-login $VAULT_ADDR
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 -batch ";project ota-plus-web;release" -Dsbt.log.noformat=true
  cache:
    paths:
      - .ivy2/
      - .sbt/

trigger dev deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - master
  variables:
    ENV: "dev"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: app
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master

trigger sit deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - deploy/sit
  variables:
    ENV: "sit"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: app
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master

veracode scan:
  # prepare and submit for static code analysis
  stage: veracode scan
  only:
    variables:
      - $VERACODE_API_ID
  image: advancedtelematic/veracode:0.1.2
  before_script:
    - tar -f scan.tar --append ota-plus-web/app/reactapp
  script:
    - java -jar /opt/veracode/veracode-wrapper.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_KEY}
      -action UploadAndScan -appname "OTA Frontend" -createprofile true -autoscan true
      -filepath scan.tar -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID} for ${CI_PROJECT_NAME} repo"
  artifacts:
    paths:
      - scan.tar

deps scan:
  # perform dependencies CVE analysis
  stage: deps scan
  only:
    - schedules
  image: advancedtelematic/gitlab-jobs:0.2.0
  script:
    - ./sbt dependencyCheckAggregate
    - mv target/scala-*/dependency-check-report.html ./depchk.html
  artifacts:
    paths:
      - depchk.html

pages:
  stage: generate pages
  only:
    - schedules
  dependencies:
    - deps scan
  script:
    - mkdir -p public
    - mv depchk.html public/index.html
  artifacts:
    paths:
      - public
    expire_in: 64 days

trigger-docsite-build:
  stage: publish-docs-if-changed
  except:
    - schedules
  only:
    refs:
      - master
    changes:
      - ota-plus-web/docs/**/*
  trigger:
    project: olp/edge/ota/documentation/ota-connect-docs
    branch: master
