= Create an environment

You may need to have different environments for pre-production and production. Instead of creating multiple accounts for each environment, you can now create up to 10 additional environments using only one account.

IMPORTANT: The limit of 10 additional environments applies even if you leave the environments that you have created. There is currently no way to delete environments.

*To create an environment:*

. Go to the https://connect.ota.here.com/#/environments[*Environments*, window="_blank"] tab.
. Click *Create environment*.
. In the *Create environment* dialog box, enter the environment name.
+
The environment name should not exceed 30 characters and can contain letters, numbers, and the following specific characters: `' " . , : ; _ - / ( )`.

. Click *Create*.
+
The page with the details about the created environment opens. In the *Members* list, next to your email, the *Creator* label appears. As an environment creator, you can leave or be removed from your additional environments. However, you cannot leave or be removed from your home environment that you get upon registration. To learn more about different types of environments, see xref:environments-intro.adoc[What is an environment].

You can now xref:manage-members.adoc[add] your colleagues to the environment.
