= Find and change environments

[NOTE]
====
This feature is in beta and is only visible to users who are part of our beta program. If you would like to join the beta program, contact us at link:mailto:otaconnect.support@here.com[otaconnect.support@here.com] to request access.
====

You can share your environment with your colleagues and become a member of other environments.

To find the list of environments to which you have access and switch between them:

1. Log in to OTA Connect.
2. In the upper-right corner, click the profile menu, and then click *Environments*.
+
On the *Environments* tab, you can find the list of environments to which you have access. The highlighted environment is your active environment.
3. To switch to a different environment, from the *Environment Name* list, select the needed environment.
+
[TIP]
====
You can also change your active environment from anywhere in the portal: under the *Support* and profile menus, point to the name of the active environment, and then select the needed environment.
====
+
The OTA Connect portal reloads, and the *Home* page of the selected environment opens. 

In the environments to which you have access, you can xref:manage-members.adoc[add and remove] members.
