= Manage members in environments

You can add colleagues to your environments to collaborate on devices, device groups, software versions, software updates, and campaigns. For example, you may need to collaborate with your developers on device provisioning. People that you want to add to your environment must have an OTA Connect account. Also, you can remove members from the environments to which you have access, but you cannot remove the owner of the environment.

*To manage members in the environments to which you have access:*

1. Log in to your https://connect.ota.here.com[OTA Connect account, window="_blank"].
2. In the upper-right corner, click the profile menu, and then click *Environments*.
3. Click the environment in which you want to manage members.
+
The page with environment details opens.
4. In the *Member* list, do one of the following:
    * To add a member:
    .. Click *Add member*.
    .. Specify the email of the user that you want to add to the environment.
    .. Click *Add*.
+
The new member appears in the *Members* section and has access to all the resources in the environment.
+
IMPORTANT: The user should be registered in OTA Connect before you add them to the environment. Otherwise, they will not see the environment. If the user is added before they are registered, for the user to see the environment, remove the user, register this user, and then add again.

    * To remove a member, next to the email of the member that you want to remove, click *Remove*, and then click *Yes, remove*.
+
You can remove a member with the *Creator* label but not the member with the *Owner* label as it is their home environment. To learn more about different types of environments, see xref:environments-intro.adoc[What is an environment].
+
The member that you removed can no longer access the resources in the environment.
