= What is device provisioning?

Before you can start working with devices, they need to be provisioned with credentials, so they can register with the OTA Connect server. Device provisioning is normally done by developers who install the OTA Connect client software and device credentials on your devices.

If you have just logged in and do not see any devices, ask your developers to provision some for you. To work together with developers on devices and their provisioning, xref:manage-members.adoc[add] developers to your environment.

Alternatively, if you feel comfortable with the Linux command line, you can provision devices yourself. The easiest way to provision a device is to simulate a device on your computer and have the OTA Connect server generate device credentials for you.

*To simulate a device:*

1. xref:create-provisioning-key.adoc[Generate and download] a provisioning key.
2. xref:getstarted::simulate-device-workstation.adoc[Simulate] the device on your workstation.

To understand how provisioning works in detail, see the xref:ota-client::client-provisioning-methods.adoc[Device Provisioning Methods] section of the OTA Connect Client guide.

// Note for client guide: Reprovisioning the same device wont override the old one, you need to delete the old one first.
