= Manage access to features

If you are an environment owner, creator, or have the *Access Manager* access rights, you can give or restrict access to features for other members of the environment. 
You cannot restrict access for environment creators and owners. They have full access to all environment features. Members with the *Fully restricted* access rights cannot use any of the environment features.

NOTE: You can restrict access to features on the OTA Connect Portal, but you cannot restrict access at the API level.

*To manage access to features:*

. Go to the https://connect.ota.here.com/#/environments[*Environments*, window="_blank"] tab.
. Click the environment in which you want to manage access to features.
+
The page with environment details opens.
. In the *Members* list, select a user for whom you want to manage access, and do one of the following:
** To give access to a feature, select a check box next to it.
+
Now, the user has access to the allowed feature in this environment.

** To restrict access to a feature, clear a check box next to it.
+
Now, the user has no access to the restricted feature in this environment on the OTA Connect Portal.