
/* Displaying dates formats */
export const CAMPAIGN_SUMMARY_CREATED_DATE_FORMAT = 'DD.MM.YYYY HH:mm';
export const CREDENTIALS_PROVISIONING_DATE_FORMAT = 'ddd MMM D YYYY HH:mm:ss';
export const DEVICE_INSTALLATION_EVENT_DATE_FORMAT = 'ddd MMM DD YYYY, h:mm:ss A';
export const DEVICE_LAST_UPDATED_DATE_FORMAT = 'ddd MMM D YYYY HH:mm:ss';
export const DEVICE_SOFTWARE_CREATED_DATE_FORMAT = 'ddd MMM DD YYYY, h:mm:ss A';
export const DEVICE_SUMMARY_DATE_FORMAT = 'ddd MMM D YYYY HH:mm:ss';
export const DEVICE_MTU_RECEIVED_AT = 'ddd MMM DD YYYY, h:mm A';
export const DEVICE_PROPERTIES_DATE_FORMAT = 'ddd MMM DD YYYY, h:mm:ss A';
export const RECENTLY_CREATED_DATE_FORMAT = 'ddd MMM D YYYY HH:mm';
export const SERVICE_TERMS_AGREED_DATE_FORMAT = 'MMM Do YYYY';
export const SOFTWARE_UPDATE_VERSIONS_DATE_FORMAT = 'ddd MMM DD YYYY, h:mm:ss A';
export const SOFTWARE_VERSION_DATE_FORMAT = 'ddd MMM DD YYYY, h:mm:ss A';
export const USAGE_ITEM_DATE_FORMAT = 'MMM YYYY';

/* Data formats */
export const CREDENTIALS_PROVISIONING_DATA_DATE_FORMAT = 'YYYY-MM-DD';
export const DEVICE_ACTIVATED_DATE_DATA_FORMAT = 'YYYYMM';
export const USAGE_DATE_DATA_FORMAT = 'YYYYMM';
export const USAGE_DATE_MONTH_DATA_FORMAT = 'MM';
export const USAGE_DATE_YEAR_DATA_FORMAT = 'YYYY';
