---
services:
  - name: sota-data
    repo: busybox
    state: present
    restart_policy: 'no'
    volumes:
      - /var/lib/mysql
      - /tmp/
      - /var/lib/sota
    command: "true"

  - name: mysql
    repo: advancedtelematic/mariadb
    ports:
      - 3306
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_user_password }}"
      MYSQL_DATABASES: "{{ db_resolver_name }} {{ db_core_name }} {{ db_core_name }}_test {{ db_resolver_name }}_test"
    volumes_from:
      - sota-data

  - name: rvi-server
    repo: advancedtelematic/rvi
    attach: true
    ports:
      - 8801
    env:
      RVI_LOGLEVEL: "debug"
    command: server

  - name: resolver
    repo: advancedtelematic/sota-resolver
    pull: false
    ports:
      - 8081
    expose:
      - "8081"
    links:
      - mysql
    env:
      HOST: 0.0.0.0
      RESOLVER_DB_URL: "jdbc:mariadb://mysql:3306/{{ db_resolver_name }}"

  - name: core
    repo: advancedtelematic/sota-core
    pull: false
    ports:
      - 8080
    expose:
      - "8080"
    links:
      - mysql
      - resolver
      - rvi-server
    env:
      HOST: 0.0.0.0
      SOTA_SERVICES_URI: "http://core:8080/rvi"
      CORE_DB_URL: "jdbc:mariadb://mysql:3306/{{ db_core_name }}"
      RESOLVER_API_URI: "http://resolver:8081"
      RVI_URI: "http://rvi-server:8801"
    volumes_from:
      - sota-data

  - name: webserver
    repo: advancedtelematic/sota-webserver
    pull: false
    links:
      - resolver
      - core
    ports:
      - 80:9000
    env:
      CORE_API_URI: "http://core:8080"
      RESOLVER_API_URI: "http://resolver:8081"
      PLAY_CRYPTO_SECRET: {{ play_crypto_secret }}

  - name: rvi-client
    repo: advancedtelematic/rvi
    attach: true
    pull: false
    ports:
      - 8901
    links: [rvi-server]
    env:
      RVI_LOGLEVEL: "debug"
      RVI_BACKEND: "rvi-server"
    command: client

  - name: sota-client-debug
    repo: advancedtelematic/sota-client-debug
    ports: [8090]
    links: [rvi-client]
    env:
      LOGLEVEL: "trace"
      RVI_ADDR: "rvi-client"
      SOTA_CLIENT_ADDR: "sota-client-debug"
      SOTA_CLIENT_PORT: "8090"

  - name: sota-migration
    repo: advancedtelematic/sota-migration
    restart_policy: 'no'
    links:
      - mysql
    env:
      RESOLVER_DB_URL: "jdbc:mariadb://mysql:3306/{{ db_resolver_name }}"
      CORE_DB_URL: "jdbc:mariadb://mysql:3306/{{ db_core_name }}"
