%% Ensure when adding entities here they match what's defined in the internal-docs repo
graph LR

web_backend --> auditor
web_backend --> auth0
web_backend --> build_server
web_backend --> core
web_backend --> crypt_service
web_backend --> device_registry
web_backend --> kafka
web_backend --> resolver
web_backend --> tuf_repo
web_backend --> user_profile

web_frontend --> auth0
web_frontend --> 3rd_party_auth_provider
web_frontend --> web_backend
